config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: %i[index show new create edit update] do
    resources :reviews, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: %w[chinese italian japanese french belgian]
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show edit update]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def show
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)

    redirect_to restaurant_path(@restaurant)
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = restaurant

    if @review.save
      redirect_to restaurant_path(restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating, :restaurant_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: ["chinese", "italian", "japanese", "french", "belgian"] %>
  <br>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render "form", restaurant: @restaurant %>

<%= link_to 'Back to list', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>RESTAURANTS LIST</h1>
<br>
<% @restaurants.each do |restaurant| %>
    <li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
  <% end %>
<br><br>
<%= link_to 'Add new restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<%= render "form", restaurant: @restaurant %>
<br>
<%= link_to 'Back to list', restaurants_path %>

app/views/restaurants/show.html.erb
<h2>RESTAURANT DETAILS</h2><br>
<p><strong>Restaurant name: </strong><%= @restaurant.name %></p>
<p><strong>Restaurant address: </strong><%= @restaurant.address %></p>
<p><strong>Restaurant phone number: </strong><%= @restaurant.phone_number %></p>
<p><strong>Restaurant category: </strong><%= @restaurant.category %></p>

<strong>Restaurant review: </strong><% reviews = Review.where(restaurant: @restaurant).order(created_at: :desc) %>
      <% reviews.each do |review| %>
        <p><%= review.content %> - <%= "*" * review.rating %></p>
      <% end %>
<br><br>
<%= link_to "Edit #{@restaurant.name}",
            edit_restaurant_path(@restaurant), class: "btn btn-primary mb-2" %>
<br>
<%= link_to "Add review for #{@restaurant.name}",
            new_restaurant_review_path(@restaurant), class: "btn btn-primary mb-2" %>
<br>
<%= link_to 'Back to list', restaurants_path %>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Create a new review", class: "btn btn-primary" %>
<% end %>
<br>
<%= link_to 'Back to list', restaurants_path %>